# Generated by Django 4.2 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicadoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('publico_objetivo', models.CharField(choices=[('todos', 'Todos los Colegios'), ('directores', 'Solo Directores y Admin'), ('premium', 'Colegios Plan Premium'), ('onboarding', 'Colegios en Onboarding'), ('morosos', 'Colegios con Pagos Pendientes'), ('profesores', 'Profesores y Docentes')], default='todos', max_length=50)),
                ('tipo_alerta', models.CharField(choices=[('informativa', 'Informativa (Azul)'), ('mantenimiento', 'Mantenimiento (Naranja)'), ('urgente', 'Urgente / Sistema (Rojo)')], default='informativa', max_length=30)),
                ('mensaje', models.TextField()),
                ('banner_flotante', models.BooleanField(default=True)),
                ('notificar_email', models.BooleanField(default=True)),
                ('bloquear_popup', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('programado', 'Programado'), ('borrador', 'Borrador')], default='enviado', max_length=20)),
                ('tasa_lectura', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comunicado Global',
                'verbose_name_plural': 'Comunicados Globales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
