# Generated by Django 4.2.23 on 2026-08-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_modulo_fecha_creacion_plan_fecha_creacion'),
        ('colegios', '0018_alter_configuracionmodulos_options_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sii_rut', models.CharField(blank=True, default='', max_length=20, verbose_name='RUT Emisor SII')),
                ('sii_razon_social', models.CharField(blank=True, default='', max_length=150, verbose_name='Razón Social SII')),
                ('sii_ambiente', models.CharField(choices=[('produccion', 'Producción (Oficial)'), ('certificacion', 'Certificación / Staging (Testing)')], default='certificacion', max_length=20, verbose_name='Ambiente SII')),
                ('sii_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Token API Facturación Electrónica')),
                ('mp_public_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Public Key (MP / Webpay)')),
                ('mp_access_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Access Token (Secret Key)')),
                ('mp_modo', models.CharField(choices=[('live', 'Live / Producción'), ('sandbox', 'Sandbox / Pruebas')], default='sandbox', max_length=20, verbose_name='Modo de Procesamiento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
        migrations.CreateModel(
            name='SolicitudNuevoColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colegio', models.CharField(max_length=150, verbose_name='Nombre del Colegio')),
                ('rut_sostenedor', models.CharField(max_length=20, verbose_name='RUT del Sostenedor')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono de Contacto')),
                ('ciudad_comuna', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad / Comuna')),
                ('nombre_administrador', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del Director / Administrador')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('notas_admin', models.TextField(blank=True, default='', verbose_name='Notas del Revisor')),
                ('colegio_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='colegios.colegio', verbose_name='Colegio Generado')),
                ('plan_solicitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_colegio', to='planes.plan', verbose_name='Plan Solicitado')),
            ],
            options={
                'verbose_name': 'Solicitud de Nuevo Colegio',
                'verbose_name_plural': 'Solicitudes de Nuevos Colegios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstadoOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion_inicial', models.BooleanField(default=False)),
                ('carga_alumnos', models.BooleanField(default=False)),
                ('capacitacion_docentes', models.BooleanField(default=False)),
                ('lanzamiento_oficial', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_onboarding', to='colegios.colegio')),
            ],
        ),
    ]
