# Generated by Django for MensajeUsuario model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_configuracionglobal_solicitudnuevocolegio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido del Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('leido', models.BooleanField(default=False, verbose_name='¿Leído?')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_usuario_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_usuario_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje de Usuario',
                'verbose_name_plural': 'Mensajes de Usuarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='mensajeusuario',
            index=models.Index(fields=['remitente', 'destinatario', 'fecha_creacion'], name='dashboard_m_remiten_5e56e3_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeusuario',
            index=models.Index(fields=['destinatario', 'leido'], name='dashboard_m_destina_8449c2_idx'),
        ),
    ]
