# Generated by Django 4.2.23 on 2026-10-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_mensajeusuario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mensajeusuario',
            new_name='dashboard_m_remiten_e98e21_idx',
            old_name='dashboard_m_remiten_5e56e3_idx',
        ),
        migrations.RenameIndex(
            model_name='mensajeusuario',
            new_name='dashboard_m_destina_def854_idx',
            old_name='dashboard_m_destina_8449c2_idx',
        ),
        migrations.AlterField(
            model_name='solicitudnuevocolegio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
