# Generated by Django 4.2.23 on 2026-08-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0009_configuracionacademica_modalidad_asistencia'),
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='colegios.asignatura'),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together={('seccion', 'asignatura', 'fecha')},
        ),
    ]
