# Generated by Django 4.2.23 on 2026-05-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT del usuario', max_length=12, null=True),
        ),
    ]
