# Generated by Django 4.2.23 on 2026-08-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pin_bloqueado_hasta',
            field=models.DateTimeField(blank=True, help_text='Bloqueo temporal por intentos fallidos', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pin_fecha_actualizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se configuró o renovó el PIN', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pin_hash',
            field=models.CharField(blank=True, help_text='Hash seguro del PIN de 4 dígitos', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pin_intentos_fallidos',
            field=models.PositiveIntegerField(default=0, help_text='Contador de intentos fallidos consecutivos'),
        ),
    ]
