# Generated by Django 4.2.23 on 2026-08-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario_pin_bloqueado_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pin_reset_codigo',
            field=models.CharField(blank=True, help_text='Código OTP de 6 dígitos para recuperación de PIN', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pin_reset_expira',
            field=models.DateTimeField(blank=True, help_text='Expiración del código OTP (10 min)', null=True),
        ),
    ]
