# Generated by Django 4.2.23 on 2026-05-23 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegios', '0002_suscripcion_colegiomodulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_solicitado', models.CharField(choices=[('profesor', 'Profesor'), ('inspector', 'Inspector'), ('director', 'Director'), ('administrativo', 'Administrativo'), ('contabilidad', 'Contabilidad'), ('otro', 'Otro')], max_length=30)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_acceso', to='colegios.colegio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Acceso',
                'verbose_name_plural': 'Solicitudes de Acceso',
            },
        ),
        migrations.CreateModel(
            name='MiembroColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('director', 'Director'), ('profesor', 'Profesor'), ('inspector', 'Inspector'), ('administrativo', 'Administrativo'), ('contabilidad', 'Contabilidad')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='colegios.colegio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_colegio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Colegio',
                'verbose_name_plural': 'Miembros de Colegio',
                'unique_together': {('usuario', 'colegio')},
            },
        ),
    ]
