# Generated by Django 4.2.23 on 2026-05-25 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0004_configuracionacademica_cursocolegio_permiso_and_more'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembrocolegio',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='colegios.rolcolegio'),
        ),
        migrations.AlterField(
            model_name='solicitudacceso',
            name='rol_solicitado',
            field=models.CharField(max_length=50),
        ),
    ]
