# Generated by Django 4.2.23 on 2026-08-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_miembrocolegio_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudacceso',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo del rechazo indicado por la dirección', null=True),
        ),
    ]
