# Generated by Django 4.2.23 on 2026-05-23 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_administrador', models.CharField(max_length=150)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('ciudad_comuna', models.CharField(max_length=100)),
                ('tipo_institucion', models.CharField(choices=[('particular', 'Particular'), ('subvencionado', 'Subvencionado'), ('municipal', 'Municipal'), ('instituto', 'Instituto'), ('otro', 'Otro')], max_length=30)),
                ('cantidad_alumnos', models.CharField(choices=[('menos_100', 'Menos de 100'), ('100_300', '100 a 300'), ('301_600', '301 a 600'), ('mas_600', 'Más de 600')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='pendiente_pago', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colegios_administrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
            },
        ),
    ]
