# Generated by Django 4.2.23 on 2026-05-23 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_facturacion', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente_pago', max_length=30)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='colegios.colegio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='ColegioModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_activos', to='colegios.colegio')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.modulo')),
            ],
            options={
                'verbose_name': 'Módulo de Colegio',
                'verbose_name_plural': 'Módulos de Colegio',
                'unique_together': {('colegio', 'modulo')},
            },
        ),
    ]
