# Generated by Django 4.2.23 on 2026-05-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0002_suscripcion_colegiomodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='eslogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='colegios/portadas/'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='colegios/logos/'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='pais',
            field=models.CharField(default='Chile', max_length=100),
        ),
        migrations.AddField(
            model_name='colegio',
            name='referencia_direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='telefono_alternativo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educativo', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('letra', models.CharField(max_length=10)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='colegios.periodoacademico')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
                ('permisos', models.JSONField(default=dict)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_configurados', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Configuración de Rol',
                'verbose_name_plural': 'Configuraciones de Roles',
            },
        ),
    ]
