# Generated by Django 4.2.23 on 2026-05-25 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_modulo_fecha_creacion_plan_fecha_creacion'),
        ('colegios', '0003_colegio_direccion_colegio_eslogan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_academico', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('periodo_academico', models.CharField(choices=[('semestres', 'Semestres'), ('trimestres', 'Trimestres'), ('anual', 'Anual')], default='semestres', max_length=20)),
                ('horario_referencial', models.CharField(blank=True, max_length=100)),
                ('nivel_parvularia', models.BooleanField(default=False)),
                ('nivel_basica', models.BooleanField(default=False)),
                ('nivel_media', models.BooleanField(default=False)),
                ('nivel_tecnico_profesional', models.BooleanField(default=False)),
                ('nivel_especial', models.BooleanField(default=False)),
                ('nivel_otro', models.BooleanField(default=False)),
                ('jornada_manana', models.BooleanField(default=False)),
                ('jornada_tarde', models.BooleanField(default=False)),
                ('jornada_completa', models.BooleanField(default=True)),
                ('jornada_vespertina', models.BooleanField(default=False)),
                ('jornada_flexible', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Académica',
                'verbose_name_plural': 'Configuraciones Académicas',
            },
        ),
        migrations.CreateModel(
            name='CursoColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('parvularia', 'Educación Parvularia'), ('basica', 'Educación Básica'), ('media', 'Educación Media'), ('tecnico_profesional', 'Técnico Profesional'), ('especial', 'Educación Especial')], max_length=30)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('desde_letra', models.CharField(default='A', max_length=1)),
                ('hasta_letra', models.CharField(default='A', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso de Colegio',
                'verbose_name_plural': 'Cursos de Colegio',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='RolColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('es_base', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol de Colegio',
                'verbose_name_plural': 'Roles de Colegio',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=False)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('puede_exportar', models.BooleanField(default=False)),
                ('puede_aprobar', models.BooleanField(default=False)),
                ('puede_enviar_mensajes', models.BooleanField(default=False)),
                ('puede_administrar', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.modulo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='colegios.rolcolegio')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('rol', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='SeccionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='colegios.cursocolegio')),
            ],
            options={
                'verbose_name': 'Sección de Curso',
                'verbose_name_plural': 'Secciones de Cursos',
                'unique_together': {('curso', 'letra')},
            },
        ),
        migrations.RemoveField(
            model_name='curso',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='colegio',
        ),
        migrations.AddField(
            model_name='colegio',
            name='color_acento',
            field=models.CharField(default='#ff6b6b', max_length=20),
        ),
        migrations.AddField(
            model_name='colegio',
            name='color_neutro',
            field=models.CharField(default='#f8fafc', max_length=20),
        ),
        migrations.AddField(
            model_name='colegio',
            name='color_principal',
            field=models.CharField(default='#7b52d9', max_length=20),
        ),
        migrations.AddField(
            model_name='colegio',
            name='color_secundario',
            field=models.CharField(default='#6a44c2', max_length=20),
        ),
        migrations.AddField(
            model_name='colegio',
            name='configuracion_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colegio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='paso_configuracion_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('pendiente_configuracion', 'Pendiente de Configuración'), ('pendiente_pago', 'Pendiente de Pago'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='pendiente_configuracion', max_length=30),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='tipo_institucion',
            field=models.CharField(choices=[('municipal', 'Municipal'), ('subvencionado', 'Subvencionado'), ('particular', 'Particular'), ('instituto', 'Instituto'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='colegio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='colegios.colegio'),
        ),
        migrations.DeleteModel(
            name='ConfiguracionRol',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='PeriodoAcademico',
        ),
        migrations.AddField(
            model_name='rolcolegio',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='colegios.colegio'),
        ),
        migrations.AddField(
            model_name='cursocolegio',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='colegios.colegio'),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='colegio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_academica', to='colegios.colegio'),
        ),
        migrations.AlterUniqueTogether(
            name='rolcolegio',
            unique_together={('colegio', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='cursocolegio',
            unique_together={('colegio', 'nombre')},
        ),
    ]
