# Generated by Django 4.2.23 on 2026-05-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0004_configuracionacademica_cursocolegio_permiso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolcolegio',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='colegios.colegio'),
        ),
    ]
