# Generated by Django 4.2.23 on 2026-05-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0005_alter_rolcolegio_colegio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursocolegio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cursocolegio',
            name='jornada',
            field=models.CharField(default='Mañana', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cursocolegio',
            unique_together={('colegio', 'nombre', 'jornada')},
        ),
    ]
