# Generated by Django 4.2.23 on 2026-08-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0008_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionacademica',
            name='modalidad_asistencia',
            field=models.CharField(choices=[('diaria', 'Asistencia Diaria General'), ('asignatura', 'Asistencia por Asignatura / Bloque')], default='asignatura', max_length=20),
        ),
    ]
