# Generated by Django 4.2.23 on 2026-08-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0009_configuracionacademica_modalidad_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionacademica',
            name='nota_minima_aprobacion',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='notificar_ausencias',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='notificar_notas_rojas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='porcentaje_asistencia_minima',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='porcentaje_exigencia',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='regla_redondeo',
            field=models.CharField(choices=[('un_decimal', 'Redondear a 1 decimal (ej: 5.65 -> 5.7)'), ('dos_decimales', 'Redondear a 2 decimales (ej: 5.65)'), ('truncado', 'Truncar sin redondear (ej: 5.69 -> 5.6)')], default='un_decimal', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='tipo_calculo_promedio',
            field=models.CharField(choices=[('ponderado', 'Promedio Ponderado por Coeficientes'), ('simple', 'Promedio Aritmético Simple')], default='ponderado', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='tipo_calificacion',
            field=models.CharField(choices=[('numerica', 'Notas Numéricas (1.0 a 7.0)'), ('conceptual', 'Evaluación Conceptual (L, PL, NL)')], default='numerica', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionacademica',
            name='visibilidad_notas_apoderados',
            field=models.CharField(choices=[('inmediata', 'Publicación Inmediata al Guardar Nota'), ('cierre_periodo', 'Solo al Cierre del Período Académico')], default='inmediata', max_length=20),
        ),
    ]
