# Generated by Django 4.2.23 on 2026-08-02 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0010_configuracionacademica_nota_minima_aprobacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('positiva', 'Anotación Positiva / Mérito'), ('negativa', 'Anotación Negativa / Falta'), ('neutra', 'Observación Neutra'), ('citacion', 'Citación a Apoderado')], default='neutra', max_length=20)),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('grave', 'Grave'), ('gravisima', 'Gravísima')], default='leve', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotaciones', to='colegios.asignatura')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='colegios.colegio')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='colegios.estudiante')),
            ],
            options={
                'verbose_name': 'Anotación de Estudiante',
                'verbose_name_plural': 'Anotaciones de Estudiantes',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
