# Generated by Django 4.2.23 on 2026-08-02 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0011_anotacionestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('clase', 'Clase / Cátedra'), ('evaluacion', 'Prueba / Evaluación'), ('reunion', 'Reunión Directiva / Apoderados'), ('actividad', 'Actividad Institucional')], default='actividad', max_length=30)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegios.asignatura')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_agenda', to='colegios.colegio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegios.cursocolegio')),
            ],
            options={
                'verbose_name': 'Evento de Agenda',
                'verbose_name_plural': 'Eventos de Agenda',
                'ordering': ['fecha_inicio', 'id'],
            },
        ),
    ]
