# Generated by Django 4.2.23 on 2026-08-02 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0012_eventoagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='es_para_todos',
            field=models.BooleanField(default=False),
        ),
    ]
