# Generated by Django 4.2.23 on 2026-08-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0013_eventoagenda_asignado_a_eventoagenda_es_para_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='dia_semana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='es_recurrente',
            field=models.BooleanField(default=False),
        ),
    ]
