# Generated by Django 4.2.23 on 2026-08-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0014_eventoagenda_dia_semana_eventoagenda_es_recurrente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccioncurso',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
