# Generated by Django 4.2.23 on 2026-08-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0015_alter_seccioncurso_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionModulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro_clases', models.BooleanField(default=False)),
                ('contabilidad', models.BooleanField(default=False)),
                ('proveedores', models.BooleanField(default=False)),
                ('simce', models.BooleanField(default=False)),
                ('mercado_publico', models.BooleanField(default=False)),
                ('comunidad', models.BooleanField(default=False)),
                ('colegio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_modulos', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Configuración de Módulos',
                'verbose_name_plural': 'Configuraciones de Módulos',
            },
        ),
    ]
