# Generated by Django 4.2.23 on 2026-08-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0015_alter_seccioncurso_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='alergias_enfermedades',
            field=models.TextField(blank=True, help_text='Alergias, condiciones médicas o medicamentos', null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='contacto_emergencia_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='diagnostico_pie',
            field=models.CharField(blank=True, help_text='Ej: TEA, TDAH, TEL, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email_apoderado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='es_pie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro / No Binarie'), ('no_informa', 'Prefiero no decir')], default='no_informa', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nacionalidad',
            field=models.CharField(default='Chilena', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre_apoderado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='observaciones_pie',
            field=models.TextField(blank=True, help_text='Adecuaciones pedagógicas y recomendaciones para docentes', null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='parentesco_apoderado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='prevision_salud',
            field=models.CharField(choices=[('fonasa', 'Fonasa'), ('isapre', 'Isapre'), ('particular', 'Particular / Seguro'), ('ninguna', 'Sin Previsión')], default='fonasa', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rut_apoderado',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_apoderado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_pie',
            field=models.CharField(blank=True, choices=[('neep', 'NEEP (Permanente)'), ('neet', 'NEET (Transitorio)'), ('sin_clasificar', 'En Proceso / Sin Clasificar')], max_length=50, null=True),
        ),
    ]
