# Generated by Django 4.2.23 on 2026-08-05 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0016_configuracionmodulos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionmodulos',
            options={},
        ),
        migrations.AlterField(
            model_name='configuracionmodulos',
            name='colegio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='colegios.colegio'),
        ),
    ]
