# Generated by Django 4.2.23 on 2026-08-15 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_modulo_fecha_creacion_plan_fecha_creacion'),
        ('solicitudes', '0002_alter_miembrocolegio_rol_and_more'),
        ('colegios', '0016_estudiante_alergias_enfermedades_estudiante_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='horas_semanales',
            field=models.PositiveIntegerField(default=4, help_text='Horas pedagógicas semanales'),
        ),
        migrations.CreateModel(
            name='MiembroPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=False)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('puede_exportar', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_individuales', to='solicitudes.miembrocolegio')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.modulo')),
            ],
            options={
                'verbose_name': 'Permiso Individual de Funcionario',
                'verbose_name_plural': 'Permisos Individuales de Funcionarios',
                'unique_together': {('miembro', 'modulo')},
            },
        ),
    ]
