# Generated by Django 4.2.23 on 2026-08-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0017_alter_configuracionmodulos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionmodulos',
            options={'verbose_name': 'Configuración de Módulos', 'verbose_name_plural': 'Configuraciones de Módulos'},
        ),
        migrations.AlterField(
            model_name='configuracionmodulos',
            name='colegio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_modulos', to='colegios.colegio'),
        ),
    ]
