# Generated by Django 4.2.23 on 2026-08-15 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0017_asignatura_horas_semanales_miembropermiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccioncurso',
            name='profesor_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_jefatura', to=settings.AUTH_USER_MODEL),
        ),
    ]
