# Generated by Django 4.2.23 on 2026-08-15 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0018_seccioncurso_profesor_jefe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso / Gasto')], default='egreso', max_length=20)),
                ('icono', models.CharField(default='bi-tag', max_length=50)),
                ('color', models.CharField(default='#7C5CFC', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_financieras', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Categoría Financiera',
                'verbose_name_plural': 'Categorías Financieras',
                'unique_together': {('colegio', 'nombre', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='CuentaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('caja_chica', 'Caja Chica'), ('cuenta_bancaria', 'Cuenta Bancaria / Corriente'), ('caja_general', 'Caja General'), ('otro', 'Otro')], default='caja_chica', max_length=30)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_financieras', to='colegios.colegio')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Financiera / Caja',
                'verbose_name_plural': 'Cuentas Financieras y Cajas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso / Gasto')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='efectivo', max_length=30)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_adjunto', models.FileField(blank=True, null=True, upload_to='finanzas/comprobantes/')),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('anulado', 'Anulado')], default='completado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='colegios.categoriafinanciera')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_financieros', to='colegios.colegio')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='colegios.cuentafinanciera')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('factura_afecta', 'Factura Electrónica (Afecta)'), ('factura_exenta', 'Factura Exenta de IVA'), ('boleta_honorarios', 'Boleta de Honorarios'), ('boleta_compra', 'Boleta de Compra / Insumos'), ('nota_credito', 'Nota de Crédito')], default='factura_afecta', max_length=30)),
                ('folio', models.CharField(max_length=50)),
                ('proveedor_nombre', models.CharField(max_length=150)),
                ('proveedor_rut', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='finanzas/facturas/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_gastos', to='colegios.colegio')),
                ('movimiento_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_vinculada', to='colegios.movimientofinanciero')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura / Documento Tributario',
                'verbose_name_plural': 'Facturas y Documentos Tributarios',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
    ]
