# Generated by Django 4.2.23 on 2026-08-15 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0019_categoriafinanciera_cuentafinanciera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='bi-box-seam', max_length=50)),
                ('color', models.CharField(default='#7C5CFC', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_inventario', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Categoría de Inventario',
                'verbose_name_plural': 'Categorías de Inventario',
                'unique_together': {('colegio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('consumible', 'Insumo Consumible / Fungible'), ('activo', 'Activo Fijo / Equipamiento / Mobiliario')], default='consumible', max_length=30)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('unidad_medida', models.CharField(default='unidades', max_length=30)),
                ('ubicacion', models.CharField(default='Bodega Principal', max_length=100)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='colegios.categoriainventario')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_inventario', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Artículo de Inventario',
                'verbose_name_plural': 'Artículos de Inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria_insumos', models.CharField(default='Papelería y Útiles', max_length=120)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada / Compra (+)'), ('salida', 'Salida / Consumo / Entrega (-)'), ('ajuste', 'Ajuste de Inventario')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('stock_resultante', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('entregado_a', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='colegios.iteminventario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_suministrados', to='colegios.proveedorcolegio'),
        ),
    ]
