# Generated by Django 4.2.23 on 2026-08-17 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0020_categoriainventario_iteminventario_proveedorcolegio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerExtracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('deportivo', 'Deportivo & Recreativo'), ('artistico', 'Artístico & Expresión'), ('cientifico', 'Científico & Tecnológico'), ('academico', 'Refuerzo Académico & Idiomas'), ('musica', 'Música & Danza'), ('social', 'Liderazgo & Medioambiente'), ('otro', 'Otro')], default='deportivo', max_length=50)),
                ('monitor_externo', models.CharField(blank=True, max_length=150, null=True)),
                ('dias_horario', models.CharField(help_text='Ej: Martes y Jueves 16:00 - 17:30', max_length=150)),
                ('lugar', models.CharField(default='Gimnasio Principal / Sala Multiuso', max_length=150)),
                ('cupo_maximo', models.IntegerField(blank=True, default=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(default='bi-star-fill', max_length=50)),
                ('color', models.CharField(default='#7C5CFC', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres_extracurriculares', to='colegios.colegio')),
                ('docente_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taller Extracurricular',
                'verbose_name_plural': 'Talleres Extracurriculares',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SesionAsistenciaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('contenido_actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_asistencia', to='colegios.tallerextracurricular')),
            ],
            options={
                'verbose_name': 'Sesión de Asistencia de Taller',
                'verbose_name_plural': 'Sesiones de Asistencia de Talleres',
                'ordering': ['-fecha', '-id'],
                'unique_together': {('taller', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres_inscritos', to='colegios.estudiante')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='colegios.tallerextracurricular')),
            ],
            options={
                'verbose_name': 'Inscripción a Taller',
                'verbose_name_plural': 'Inscripciones a Talleres',
                'ordering': ['estudiante__nombre_completo'],
                'unique_together': {('taller', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='DetalleAsistenciaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tarde', 'Atrasado'), ('justificado', 'Justificado')], default='presente', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_taller', to='colegios.estudiante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='colegios.sesionasistenciataller')),
            ],
            options={
                'verbose_name': 'Detalle de Asistencia de Taller',
                'verbose_name_plural': 'Detalles de Asistencia de Talleres',
                'unique_together': {('sesion', 'estudiante')},
            },
        ),
    ]
