# Generated by Django 4.2.23 on 2026-08-17 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0021_tallerextracurricular_sesionasistenciataller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsayoSIMCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('asignatura', models.CharField(choices=[('lectura', 'Lectura / Lenguaje'), ('matematica', 'Matemática'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia, Geografía y Cs. Sociales'), ('otro', 'Otro Instrumento / DIA')], default='matematica', max_length=30)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('total_preguntas', models.PositiveIntegerField(default=35)),
                ('puntaje_base', models.PositiveIntegerField(default=150)),
                ('puntaje_max', models.PositiveIntegerField(default=350)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos_simce', to='colegios.colegio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos_simce', to='colegios.cursocolegio')),
            ],
            options={
                'verbose_name': 'Ensayo SIMCE',
                'verbose_name_plural': 'Ensayos SIMCE',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PuntajeHistoricoSIMCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('nivel_escolar', models.CharField(max_length=60)),
                ('asignatura', models.CharField(max_length=60)),
                ('puntaje_colegio', models.PositiveIntegerField()),
                ('puntaje_gse', models.PositiveIntegerField(default=255)),
                ('puntaje_nacional', models.PositiveIntegerField(default=250)),
                ('nivel_insuficiente_pct', models.DecimalField(decimal_places=1, default=20.0, max_digits=5)),
                ('nivel_elemental_pct', models.DecimalField(decimal_places=1, default=45.0, max_digits=5)),
                ('nivel_adecuado_pct', models.DecimalField(decimal_places=1, default=35.0, max_digits=5)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_simce', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Puntaje Histórico SIMCE',
                'verbose_name_plural': 'Puntajes Históricos SIMCE',
                'ordering': ['-anio', 'nivel_escolar', 'asignatura'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEnsayoSIMCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas_correctas', models.PositiveIntegerField(default=0)),
                ('porcentaje_logro', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('puntaje_simce', models.PositiveIntegerField(default=200)),
                ('nivel_aprendizaje', models.CharField(choices=[('insuficiente', 'Insuficiente'), ('elemental', 'Elemental'), ('adecuado', 'Adecuado')], default='elemental', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='colegios.ensayosimce')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_simce', to='colegios.estudiante')),
            ],
            options={
                'verbose_name': 'Resultado Ensayo SIMCE',
                'verbose_name_plural': 'Resultados Ensayos SIMCE',
                'ordering': ['estudiante__nombre_completo'],
                'unique_together': {('ensayo', 'estudiante')},
            },
        ),
    ]
