# Generated by Django 4.2.23 on 2026-08-21 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0018_alter_configuracionmodulos_options_and_more'),
        ('colegios', '0022_ensayosimce_puntajehistoricosimce_and_more'),
    ]

    operations = [
    ]
