# Generated by Django 4.2.23 on 2026-08-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0023_merge_20260820_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoagenda',
            name='dia_semana',
            field=models.IntegerField(blank=True, help_text='0=Lunes, 1=Martes, 2=Miércoles, 3=Jueves, 4=Viernes', null=True),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='tipo',
            field=models.CharField(choices=[('clase', 'Clase / Horario Semanal'), ('reunion_apoderados', 'Reunión de Apoderados'), ('consejo_profesores', 'Consejo de Profesores / UTP'), ('entrevista', 'Entrevista Individual (Apoderado / PIE)'), ('evaluacion', 'Prueba / Evaluación'), ('actividad', 'Actividad Institucional / Acto'), ('feriado', 'Feriado Escolar / Suspensión'), ('reunion', 'Reunión General')], default='actividad', max_length=50),
        ),
    ]
