# Generated by Django 4.2.23 on 2026-08-28 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0024_alter_eventoagenda_dia_semana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion_proveedor', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_cotizacion', models.DateField(default=django.utils.timezone.now)),
                ('validez_dias', models.PositiveIntegerField(default=30)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('plazo_entrega_dias', models.PositiveIntegerField(default=5)),
                ('condiciones_pago', models.CharField(default='Transferencia 30 días', max_length=120)),
                ('incluye_despacho', models.BooleanField(default=True)),
                ('costo_despacho', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='compras/cotizaciones/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('es_ganadora', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotización de Proveedor',
                'verbose_name_plural': 'Cotizaciones de Proveedores',
                'ordering': ['monto_total', 'plazo_entrega_dias'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_fondo', models.CharField(choices=[('subvencion_general', 'Subvención General MINEDUC'), ('sep', 'Subvención Escolar Preferencial (SEP)'), ('pie', 'Programa de Integración Escolar (PIE)'), ('mantenimiento', 'Fondo de Mantenimiento'), ('pro_retencion', 'Fondo Pro-Retención'), ('fondos_propios', 'Fondos Propios / Financiamiento Compartido')], default='subvencion_general', max_length=30)),
                ('centro_costo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_cotizacion', 'En Cotización (Solicitando Ofertas)'), ('evaluacion', 'En Evaluación (Cotizaciones Recibidas)'), ('adjudicado', 'Adjudicado (Proveedor Seleccionado)'), ('orden_compra_emitida', 'Orden de Compra Emitida'), ('recepcionado', 'Recepcionado Conforme (Ingresado a Stock)'), ('anulado', 'Anulado / Cancelado')], default='en_cotizacion', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite_cotizacion', models.DateField(blank=True, null=True)),
                ('justificacion_adjudicacion', models.TextField(blank=True, null=True)),
                ('fecha_adjudicacion', models.DateTimeField(blank=True, null=True)),
                ('numero_orden_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision_oc', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_recepcion', models.TextField(blank=True, null=True)),
                ('numero_guia_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('adjudicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_adjudicados_por', to=settings.AUTH_USER_MODEL)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_compra', to='colegios.colegio')),
                ('cotizacion_ganadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_adjudicados', to='colegios.cotizacionproveedor')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_compra_creados', to=settings.AUTH_USER_MODEL)),
                ('recepcionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_recepcionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso de Compra & Cotización',
                'verbose_name_plural': 'Procesos de Compra & Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemProcesoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('unidad_medida', models.CharField(default='unidades', max_length=40)),
                ('especificaciones_tecnicas', models.TextField(blank=True, null=True)),
                ('item_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_compra', to='colegios.iteminventario')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='colegios.procesocompra')),
            ],
            options={
                'verbose_name': 'Ítem de Proceso de Compra',
                'verbose_name_plural': 'Ítems de Proceso de Compra',
            },
        ),
        migrations.AddField(
            model_name='cotizacionproveedor',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='colegios.procesocompra'),
        ),
        migrations.AddField(
            model_name='cotizacionproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_emitidas', to='colegios.proveedorcolegio'),
        ),
        migrations.AddField(
            model_name='cotizacionproveedor',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
