# Generated by Django 4.2.23 on 2026-08-28 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0025_cotizacionproveedor_procesocompra_itemprocesocompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentafinanciera',
            name='fondo_asociado',
            field=models.CharField(choices=[('sep', 'Fondos SEP'), ('pie', 'Fondos PIE'), ('subvencion_general', 'Subvención General'), ('mantenimiento', 'Fondo Mantenimiento'), ('fondos_propios', 'Fondos Propios / Centro de Padres'), ('otro', 'Otro')], default='fondos_propios', max_length=30),
        ),
        migrations.AddField(
            model_name='facturagasto',
            name='clasificacion_supereduc',
            field=models.CharField(choices=[('pedagogico', 'Insumos & Recursos Pedagógicos / Aula'), ('utiles_escolares', 'Útiles Escolares & Materiales para Estudiantes'), ('equipamiento', 'Equipamiento Tecnológico y Mobiliario'), ('infraestructura', 'Mantenimiento, Obras Menores y Reparaciones'), ('psicosocial', 'Acompañamiento Psicosocial & Convivencia'), ('remuneraciones', 'Honorarios & Talleres Especializados'), ('operacional', 'Gastos Operacionales & Servicios'), ('otro', 'Otro Gasto Educativo Autorizado')], default='pedagogico', max_length=30),
        ),
        migrations.AddField(
            model_name='facturagasto',
            name='rendido_supereduc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facturagasto',
            name='tipo_fondo',
            field=models.CharField(choices=[('sep', 'Subvención Escolar Preferencial (SEP)'), ('pie', 'Programa de Integración Escolar (PIE)'), ('subvencion_general', 'Subvención General / Regular'), ('mantenimiento', 'Fondo de Mantenimiento e Infraestructura'), ('fondos_propios', 'Fondos Propios / Centro de Padres / Donaciones'), ('otro', 'Otro Fondo / Convenio')], default='subvencion_general', max_length=30),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='clasificacion_supereduc',
            field=models.CharField(choices=[('pedagogico', 'Insumos & Recursos Pedagógicos / Aula'), ('utiles_escolares', 'Útiles Escolares & Materiales para Estudiantes'), ('equipamiento', 'Equipamiento Tecnológico y Mobiliario'), ('infraestructura', 'Mantenimiento, Obras Menores y Reparaciones'), ('psicosocial', 'Acompañamiento Psicosocial & Convivencia'), ('remuneraciones', 'Honorarios & Talleres Especializados'), ('operacional', 'Gastos Operacionales & Servicios'), ('otro', 'Otro Gasto Educativo Autorizado')], default='pedagogico', max_length=30),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='numero_rendicion_folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='rendido_supereduc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='tipo_fondo',
            field=models.CharField(choices=[('sep', 'Subvención Escolar Preferencial (SEP)'), ('pie', 'Programa de Integración Escolar (PIE)'), ('subvencion_general', 'Subvención General / Regular'), ('mantenimiento', 'Fondo de Mantenimiento e Infraestructura'), ('fondos_propios', 'Fondos Propios / Centro de Padres / Donaciones'), ('otro', 'Otro Fondo / Convenio')], default='subvencion_general', max_length=30),
        ),
        migrations.AlterField(
            model_name='cuentafinanciera',
            name='tipo',
            field=models.CharField(choices=[('caja_chica_utiles', 'Caja Chica Útiles Escolares & Fungibles'), ('caja_chica_convivencia', 'Caja Chica Convivencia & Inspectoría'), ('caja_chica_ciencias', 'Caja Chica Ciencias / Laboratorios'), ('caja_chica_rectoria', 'Caja Chica Dirección / Rectoría'), ('caja_chica', 'Caja Chica General / Departamentos'), ('subvencion_sep', 'Bolsa Subvención Escolar Preferencial (SEP)'), ('subvencion_pie', 'Bolsa Programa de Integración Escolar (PIE)'), ('subvencion_general', 'Bolsa Subvención General / Regular'), ('fondo_mantenimiento', 'Fondo Mantenimiento e Infraestructura'), ('cuenta_bancaria', 'Cuenta Bancaria / Corriente'), ('caja_general', 'Caja General'), ('otro', 'Otro')], default='caja_chica', max_length=35),
        ),
        migrations.CreateModel(
            name='ProyectoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_fondo', models.CharField(choices=[('sep', 'Subvención Escolar Preferencial (SEP)'), ('pie', 'Programa de Integración Escolar (PIE)'), ('subvencion_general', 'Subvención General / Regular'), ('mantenimiento', 'Fondo de Mantenimiento e Infraestructura'), ('fondos_propios', 'Fondos Propios / Centro de Padres / Donaciones'), ('otro', 'Otro Fondo / Convenio')], default='sep', max_length=30)),
                ('categoria_supereduc', models.CharField(choices=[('pedagogico', 'Insumos & Recursos Pedagógicos / Aula'), ('utiles_escolares', 'Útiles Escolares & Materiales para Estudiantes'), ('equipamiento', 'Equipamiento Tecnológico y Mobiliario'), ('infraestructura', 'Mantenimiento, Obras Menores y Reparaciones'), ('psicosocial', 'Acompañamiento Psicosocial & Convivencia'), ('remuneraciones', 'Honorarios & Talleres Especializados'), ('operacional', 'Gastos Operacionales & Servicios'), ('otro', 'Otro Gasto Educativo Autorizado')], default='pedagogico', max_length=30)),
                ('presupuesto_asignado', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificacion', 'En Planificación'), ('en_ejecucion', 'En Ejecución'), ('rendido', 'Rendido / En Verificación'), ('cerrado', 'Cerrado / Completado')], default='en_ejecucion', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_escolares', to='colegios.colegio')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto Escolar / Centro de Costo',
                'verbose_name_plural': 'Proyectos Escolares y Centros de Costo',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.AddField(
            model_name='facturagasto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='colegios.proyectoescolar'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='colegios.proyectoescolar'),
        ),
    ]
