# Generated by Django 4.2.23 on 2026-08-28 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0026_cuentafinanciera_fondo_asociado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.PositiveIntegerField(default=1)),
                ('nombre', models.CharField(help_text='Ej: 1° Bloque, Recreo Mañana', max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('clase', 'Clase Pedagógica'), ('recreo', 'Recreo / Pausa'), ('almuerzo', 'Almuerzo')], default='clase', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Bloque Horario',
                'verbose_name_plural': 'Bloques Horarios',
                'ordering': ['orden', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], default=1)),
                ('sala', models.CharField(blank=True, help_text='Ej: Sala 102, Lab Ciencias, Cancha', max_length=50, null=True)),
                ('color', models.CharField(default='#7C5CFC', help_text='Color hexadecimal para grilla', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_asignatura', to='colegios.asignatura')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_bloque', to='colegios.bloquehorario')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_clases', to='colegios.colegio')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_horario', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_seccion', to='colegios.seccioncurso')),
            ],
            options={
                'verbose_name': 'Horario de Clase',
                'verbose_name_plural': 'Horarios de Clases',
                'ordering': ['dia_semana', 'bloque__orden', 'bloque__hora_inicio'],
                'unique_together': {('colegio', 'seccion', 'bloque', 'dia_semana')},
            },
        ),
    ]
