# Generated by Django 4.2.23 on 2026-08-28 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0027_bloquehorario_horarioclase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaEstudiantePIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nee', models.CharField(choices=[('transitoria', 'NEE Transitoria (NEET)'), ('permanente', 'NEE Permanente (NEEP)')], default='transitoria', max_length=20)),
                ('diagnostico', models.CharField(choices=[('DEA', 'Dificultad Específica del Aprendizaje (DEA)'), ('TEL_EXPRESIVO', 'Trastorno Específico del Lenguaje (TEL Expresivo)'), ('TEL_MIXTO', 'Trastorno Específico del Lenguaje (TEL Mixto)'), ('TDAH', 'Trastorno por Déficit Atencional con/sin Hiperactividad (TDA/TDAH)'), ('FIL', 'Funcionamiento Intelectual Limítrofe (FIL)'), ('TEA', 'Trastorno del Espectro Autista (TEA)'), ('DI_LEVE', 'Discapacidad Intelectual Leve'), ('DI_MODERADA', 'Discapacidad Intelectual Moderada'), ('DISCAPACIDAD_VISUAL', 'Discapacidad Visual / Baja Visión / Ceguera'), ('DISCAPACIDAD_AUDITIVA', 'Discapacidad Auditiva / Hipoacusia / Sordera'), ('DISCAPACIDAD_MOTORA', 'Discapacidad Motora / Física'), ('MULTIDEFICIT', 'Multidéficit'), ('OTRO', 'Otro Diagnóstico Clínico')], max_length=30)),
                ('diagnostico_personalizado', models.CharField(blank=True, help_text='Especificación médica o neurólogo si aplica', max_length=200, null=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_revaluacion', models.DateField(blank=True, help_text='Fecha máxima para informe de reevaluación integral', null=True)),
                ('requiere_paci', models.BooleanField(default=True, help_text='Indica si cuenta con Plan de Adecuación Curricular Individual')),
                ('activo', models.BooleanField(default=True)),
                ('informe_medico_pdf', models.FileField(blank=True, null=True, upload_to='pie/informes/')),
                ('observaciones_ingreso', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_pie', to='colegios.colegio')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_pie', to='colegios.estudiante')),
                ('profesional_a_cargo', models.ForeignKey(blank=True, help_text='Educadora Diferencial o Psicopedagoga a cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_pie_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Estudiante PIE',
                'verbose_name_plural': 'Fichas de Estudiantes PIE',
                'ordering': ['estudiante__nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroLeccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('oa_codigo', models.CharField(blank=True, help_text='Ej: OA 04, OA 07', max_length=80, null=True)),
                ('contenido_tratado', models.TextField(help_text='Descripción pedagógica del contenido impartido en la clase')),
                ('actividad_tipo', models.CharField(choices=[('catedra', 'Clase Expositiva / Cátedra'), ('grupal', 'Trabajo Colaborativo / Grupal'), ('laboratorio', 'Laboratorio / Práctico'), ('evaluacion', 'Evaluación / Prueba / Control'), ('taller', 'Taller de Ejercitación'), ('salida', 'Salida a Terreno / Actividad Externa')], default='catedra', max_length=30)),
                ('observaciones', models.TextField(blank=True, help_text='Incidentes, retrasos o notas pedagógicas', null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('hash_firma', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leccionarios', to='colegios.asignatura')),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegios.bloquehorario')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leccionarios', to='colegios.colegio')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leccionarios_firmados', to=settings.AUTH_USER_MODEL)),
                ('horario_clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leccionarios', to='colegios.horarioclase')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leccionarios', to='colegios.seccioncurso')),
            ],
            options={
                'verbose_name': 'Registro de Leccionario',
                'verbose_name_plural': 'Registros de Leccionario',
                'ordering': ['-fecha', '-bloque__orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_unidad', models.CharField(help_text='Ej: Unidad 1: Álgebra y Ecuaciones Lineales', max_length=200)),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre')], default=1)),
                ('anio_lectivo', models.PositiveIntegerField(default=2026)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('oas_curriculares', models.TextField(help_text='Objetivos de Aprendizaje MINEDUC abordados')),
                ('estrategias_metodologicas', models.TextField(blank=True, null=True)),
                ('evaluacion_descripcion', models.TextField(blank=True, help_text='Instrumentos y formas de evaluación', null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada a UTP'), ('aprobada', 'Aprobada por UTP'), ('observada', 'Con Observaciones')], default='borrador', max_length=20)),
                ('feedback_utp', models.TextField(blank=True, help_text='Retroalimentación o correcciones solicitadas por UTP', null=True)),
                ('fecha_revision_utp', models.DateTimeField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='planificaciones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='colegios.asignatura')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='colegios.colegio')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_docente', to=settings.AUTH_USER_MODEL)),
                ('revisado_por_utp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones_auditadas', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='colegios.seccioncurso')),
            ],
            options={
                'verbose_name': 'Planificación Curricular',
                'verbose_name_plural': 'Planificaciones Curriculares',
                'ordering': ['-anio_lectivo', 'semestre', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanAdecuacionCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.PositiveIntegerField(default=2026)),
                ('tiempo_adicional', models.BooleanField(default=True, help_text='Tiempo adicional en evaluaciones')),
                ('adaptacion_materiales', models.TextField(blank=True, help_text='Uso de material concreto, letra aumentada, apoyos visuales', null=True)),
                ('espacio_evaluacion', models.TextField(blank=True, help_text='Ubicación preferencial en sala o aula de recursos', null=True)),
                ('graduacion_complejidad', models.TextField(blank=True, help_text='Graduación o simplificación de exigencia en OAs', null=True)),
                ('priorizacion_objetivos', models.TextField(blank=True, help_text='OAs prioritarios focalizados', null=True)),
                ('estrategias_evaluacion', models.TextField(help_text='Rúbricas adaptadas, pruebas orales, ponderación flexible')),
                ('aprobado_utp', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacis_aprobados', to=settings.AUTH_USER_MODEL)),
                ('asignatura', models.ForeignKey(blank=True, help_text='Asignatura específica o General', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegios.asignatura')),
                ('ficha_pie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacis', to='colegios.fichaestudiantepie')),
            ],
            options={
                'verbose_name': 'Plan de Adecuación Curricular (PACI)',
                'verbose_name_plural': 'Planes de Adecuación Curricular (PACI)',
                'ordering': ['-anio_lectivo', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AtencionEspecialistaPIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_especialista', models.CharField(choices=[('educadora_diferencial', 'Educadora Diferencial'), ('psicologo', 'Psicólogo / Psicóloga'), ('fonoaudiologo', 'Fonoaudiólogo / Fonoaudióloga'), ('terapeuta_ocupacional', 'Terapeuta Ocupacional'), ('psicopedagogo', 'Psicopedagogo / Psicopedagoga'), ('otro', 'Otro Profesional de Apoyo')], default='educadora_diferencial', max_length=30)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_sesion', models.CharField(choices=[('aula_recursos', 'Aula de Recursos (Apoyo Específico)'), ('aula_regular', 'Aula Regular (Co-Docencia / Acompañamiento)'), ('individual', 'Sesión Individual / Taller Especialista'), ('apoderado', 'Entrevista con Apoderado / Familia'), ('equipo_aula', 'Reunión de Trabajo Colaborativo')], default='aula_recursos', max_length=25)),
                ('objetivo_trabajado', models.CharField(help_text='Habilidad o contenido trabajado en la sesión', max_length=250)),
                ('resumen_intervencion', models.TextField(help_text='Detalle de actividades realizadas y desempeño del estudiante')),
                ('acuerdos_pedagogicos', models.TextField(blank=True, help_text='Estrategias o acuerdos para el docente de aula o la familia', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_pie_realizadas', to=settings.AUTH_USER_MODEL)),
                ('ficha_pie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='colegios.fichaestudiantepie')),
            ],
            options={
                'verbose_name': 'Atención de Especialista PIE',
                'verbose_name_plural': 'Atenciones de Especialistas PIE',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
