# Generated by Django 4.2.23 on 2026-08-30 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0028_fichaestudiantepie_registroleccionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(choices=[('superadmin', 'Super Admin'), ('colegio', 'Colegio')], default='superadmin', max_length=20, verbose_name='Remitente')),
                ('contenido', models.TextField(verbose_name='Contenido del Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='¿Leído?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='colegios.colegio', verbose_name='Colegio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_chat_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
