# Generated by Django 4.2.23 on 2026-08-02 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegios', '0010_configuracionacademica_nota_minima_aprobacion_and_more'),
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionBoletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_nombre', models.CharField(default='1° Semestre', max_length=50)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_boletin', to='colegios.colegio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_boletin', to='colegios.estudiante')),
            ],
            options={
                'verbose_name': 'Observación de Boletín',
                'verbose_name_plural': 'Observaciones de Boletín',
                'unique_together': {('estudiante', 'periodo_nombre')},
            },
        ),
    ]
